import os
import re
import json
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def groq_signal(text):
    """
    Signal 1: asks the LLM to rate how likely the text is AI-generated.
    Returns (score, reason) where score is a float 0.0-1.0.
    """
    prompt = f"""You are analyzing a piece of writing to judge whether it was written by a human or generated by an AI language model.

Rate how likely this text is AI-generated on a scale from 0.0 (definitely human-written) to 1.0 (definitely AI-generated).

Respond with ONLY a JSON object in this exact format, no other text, no markdown fences:
{{"score": 0.0, "reason": "brief one-sentence explanation"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=150,
    )

    raw = response.choices[0].message.content.strip()

    try:
        cleaned = re.sub(r"^```(json)?\s*|\s*```$", "", raw.strip())
        parsed = json.loads(cleaned)
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        reason = parsed.get("reason", "")
    except (json.JSONDecodeError, ValueError, TypeError):
        score = 0.5
        reason = f"Could not parse model response: {raw[:100]}"

    return score, reason

def stylometric_signal(text):
    """
    Signal 2: pure-Python stylometric heuristics.
    Computes sentence-length variance, type-token ratio, and punctuation
    density, then combines them into a single 0.0-1.0 AI-likelihood score.

    Higher score = more uniform/less varied = more "AI-like" by this signal.
    Returns (score, details) where details is a dict of the raw sub-metrics.
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())

    if len(sentences) < 2 or len(words) < 5:
        return 0.5, {
            "note": "text too short for reliable stylometric analysis",
            "sentence_count": len(sentences),
            "word_count": len(words),
        }

    sentence_lengths = [len(re.findall(r"\b[a-zA-Z']+\b", s)) for s in sentences]
    mean_len = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    std_dev = variance ** 0.5
    length_uniformity_score = max(0.0, min(1.0, 1 - (std_dev / 8)))

    ttr = len(set(words)) / len(words)
    ttr_score = max(0.0, min(1.0, 1 - ttr))

    punct_count = len(re.findall(r'[,;:\-"\'()]', text))
    punct_density = punct_count / max(1, len(words))
    punct_score = max(0.0, min(1.0, 1 - min(punct_density * 10, 1.0)))

    style_score = (
        0.5 * length_uniformity_score +
        0.35 * ttr_score +
        0.15 * punct_score
    )

    details = {
        "sentence_count": len(sentences),
        "word_count": len(words),
        "sentence_length_std_dev": round(std_dev, 2),
        "type_token_ratio": round(ttr, 3),
        "punctuation_density": round(punct_density, 3),
    }

    return round(style_score, 3), details